tax_table = {
    "Jan": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Feb": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Mar": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Apr": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "May": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Jun": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Jul": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Aug": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Sep": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Oct": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Nov": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
    "Dec": {
        "sell_total": 0,
        "profit": 0,
        "tax": 0,
        "foreign_exch_total": 0,
        "status": "ISENTO",
    },
}
