<<<<<<< HEAD:migrations/versions/78a2700ab92e_.py
"""empty message

Revision ID: 78a2700ab92e
Revises: 
Create Date: 2021-07-13 17:37:41.805598
=======
"""create tables

<<<<<<< HEAD:migrations/versions/9b96e6419495_creating_tables.py
Revision ID: 9b96e6419495
Revises: 
Create Date: 2021-07-13 13:54:41.432326
=======
Revision ID: 51c134fdd703
Revises: 
Create Date: 2021-07-13 11:47:22.575658
>>>>>>> 19a66eac886770e74fcfc59786cfd0fb9f2a10ec:migrations/versions/51c134fdd703_create_tables.py
>>>>>>> develop:migrations/versions/9b96e6419495_creating_tables.py

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
<<<<<<< HEAD:migrations/versions/78a2700ab92e_.py
revision = '78a2700ab92e'
=======
<<<<<<< HEAD:migrations/versions/9b96e6419495_creating_tables.py
revision = '9b96e6419495'
=======
revision = '51c134fdd703'
>>>>>>> 19a66eac886770e74fcfc59786cfd0fb9f2a10ec:migrations/versions/51c134fdd703_create_tables.py
>>>>>>> develop:migrations/versions/9b96e6419495_creating_tables.py
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ptax',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('sell_rate', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('last_name', sa.String(length=511), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=511), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('fiat', sa.String(), nullable=False),
    sa.Column('price_per_coin', sa.Float(), nullable=False),
    sa.Column('avg_price_brl', sa.Float(), nullable=False),
    sa.Column('avg_price_usd', sa.Float(), nullable=False),
    sa.Column('net_quantity', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('foreign_exch', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('sell_total', sa.Float(), nullable=False),
    sa.Column('profit', sa.Float(), nullable=False),
    sa.Column('foreign_exch_total', sa.Float(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounting')
    op.drop_table('transaction')
    op.drop_table('user')
    op.drop_table('ptax')
    op.drop_table('coins_list')
    # ### end Alembic commands ###
