"""create table coins list

Revision ID: 9fb33c373a7e
Revises: f14c822f7938
Create Date: 2021-07-09 16:44:28.657677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb33c373a7e'
down_revision = 'f14c822f7938'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(), nullable=False),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins_list')
    # ### end Alembic commands ###
