"""empty message

Revision ID: f626cad9a27f
Revises: 
Create Date: 2021-07-14 18:18:48.702392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f626cad9a27f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coins_historical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coin', sa.String(length=150), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('coins_historical')
    # ### end Alembic commands ###
